### ISSUE TITLE
Difficult to reproduce error

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsims#14] opened 2021-05-21 09:40 UTC
Running large numbers of replicate simulations using multiple cores, simulations will fall over at unpredictable stages, leaving only a cryptic message:

- ` Error in checkForRemoteErrors(val) : 
  one node produced an error: 'data' must be of a vector type, was 'NULL'`

Error most often occurs when using the default number of cores (nmax-1).  Reducing the number of cores used diminishes the frequency of the crashes, but does not eliminate crashes. I've only tried this on my home computer (4 cores, 8GB memory), it could be that my machine simply isn't up to the job.

Code below (using NorthSea shape file from March workshop) might permit duplication of the problem

```
## ----setup, include=FALSE----------------------------------------------------------------
knitr::opts_chunk$set(echo = TRUE)


## ----------------------------------------------------------------------------------------
library(dsims)
library(leaflet)
library(knitr)
library(sf)


## ----studyarea---------------------------------------------------------------------------
northsea <- make.region(region.name = "minkes",
                      shape = "C:\\Users\\erexs\\Documents\\simulation-strata\\shapefiles\\Strataprj.shp",
                      strata.name = c("South", "North"),
                      units = "km")


## ----leafletmap--------------------------------------------------------------------------
m <- leaflet() %>% addProviderTiles(providers$Esri.OceanBasemap)
m <- m %>% 
  setView(1.4, 55.5, zoom=5)
minkes <- read_sf("C:\\Users\\erexs\\Documents\\simulation-strata\\shapefiles\\Strataprj.shp")
study.area.trans <- st_transform(minkes, '+proj=longlat +datum=WGS84')
m <- addPolygons(m, data=study.area.trans$geometry, weight=2)
m


## ----popspec-----------------------------------------------------------------------------
areas <- northsea@area
prop.south <- areas[1]/sum(areas)
prop.north <- areas[2]/sum(areas)
total.abundance <- 3000
abund.south <- round(total.abundance * prop.south)
abund.north <- round(total.abundance * prop.north)
constant <- make.density(region = northsea, x.space = 10, constant = 1)
minkepop <- make.population.description(region = northsea,
                                           density = constant,
                                           N = c(abund.south, abund.north))


## ----survdesign--------------------------------------------------------------------------
coverage.grid <- make.coverage(northsea, n.grid.points = 100)
equal.cover <- make.design(region = northsea,
                           transect.type = "line",
                           design = "systematic",
                           samplers=40, 
                           design.angle = c(50, 40),
                           truncation = 0.8,
                           coverage.grid = coverage.grid)


## ----designprop--------------------------------------------------------------------------
design.properties <- run.coverage(equal.cover, reps = 10, quiet=TRUE)
mine <- data.frame(Num.transects=design.properties@design.statistics$sampler.count[3,],
                   Proportion.covered=design.properties@design.statistics$p.cov.area[3,])
kable(mine)


## ----whatanalysis------------------------------------------------------------------------
pooled.hn <- make.ds.analysis(dfmodel = list(~1),
                                key = "hn",
                                criteria = "AIC",
                                truncation = 0.8)
strat.specific.or.not <- make.ds.analysis(dfmodel = list(~1, ~Region.Label),
                                key = "hn",
                                criteria = "AIC",
                                truncation = 0.8)


## ----sigma-------------------------------------------------------------------------------
delta.multiplier <- c(seq(from=0.4, to=0.8, by=0.2),
                      seq(from=0.85, to=1.15, by=0.1),
                      seq(from=1.2, to=2.4, by=0.2))
sigma.south <- 0.6
north.sigma <- sigma.south*delta.multiplier


## ----sigmarange--------------------------------------------------------------------------
hn <- function(sigma, x) {return(exp(-x^2/(2*sigma^2)))}
for (i in seq_along(north.sigma)) {
  curve(hn(north.sigma[i],x),from=0,to=0.8,add=i!=1,  
        xlab="Distance", ylab="Detection probability", 
        main="Range of detection probability disparity\nSouth function in blue")
}
curve(hn(sigma.south,x),from=0,to=0.8, lwd=2, col='blue', add=TRUE)


## ----loopsigma---------------------------------------------------------------------------
equalcover <- list()
whichmodel <- list()
num.sims <- 90
for (i in seq_along(delta.multiplier)) {
  sigma.strata <- c(sigma.south, sigma.south*delta.multiplier[i])
  detect <- make.detectability(key.function = "hn",
                               scale.param = sigma.strata,
                               truncation = 0.8)
  equalcover.sim <- make.simulation(reps = num.sims,
                                    design = equal.cover,
                                    population.description = minkepop,
                                    detectability = detect,
                                    ds.analysis = pooled.hn)
  whichmodel.sim <- make.simulation(reps = num.sims,
                                    design = equal.cover,
                                    population.description = minkepop,
                                    detectability = detect,
                                    ds.analysis = strat.specific.or.not)
  equalcover[[i]] <- run.simulation(equalcover.sim, run.parallel = TRUE, max.cores=2)
  whichmodel[[i]] <- run.simulation(whichmodel.sim, run.parallel = TRUE, max.cores=2)
}


## ----meaning, echo=FALSE-----------------------------------------------------------------
pctbias <- mat.or.vec(length(delta.multiplier),3)
ci.cover <- mat.or.vec(length(delta.multiplier),3)
num.detects <- mat.or.vec(length(delta.multiplier),3)
modelsel <- mat.or.vec(length(delta.multiplier),1)
bias.modsel <- mat.or.vec(length(delta.multiplier),3)
cover.modsel <- mat.or.vec(length(delta.multiplier),3)
for (i in seq_along(delta.multiplier)) {
  simsum <- summary(equalcover[[i]], description.summary=FALSE)
  selsum <- summary(whichmodel[[i]], description.summary=FALSE)
  pctbias[i, ] <- simsum@individuals$D[,3]
  ci.cover[i, ] <- simsum@individuals$D[,5]
  num.detects[i, ] <- simsum@individuals$summary[,3]
  bias.modsel[i, ] <- selsum@individuals$D[,3]
  cover.modsel[i, ] <- selsum@individuals$D[,5]
  modelsel[i] <- sum(whichmodel[[i]]@results$Detection[1,5, 1:num.sims]==2) / num.sims
}
pooled <- as.data.frame(cbind(pctbias, ci.cover, num.detects, modelsel))
names(pooled) <- c("Bias.N", "Bias.S", "Bias.Tot",
                "CICover.N", "CICover.S", "CICover.Tot",
                "Detects.N", "Detects.S", "Detects.Tot", "Prop.strat.model")
row.names(pooled) <- delta.multiplier
kable(pooled, digits=c(rep(1,3), rep(2,3), rep(0,3), 2), 
      caption="Results using pooled detection function")


## ----selection, echo=FALSE---------------------------------------------------------------
with.selection <- as.data.frame(cbind(bias.modsel, cover.modsel))
names(with.selection) <- c("Bias.N", "Bias.S", "Bias.Tot",
                "CICover.N", "CICover.S", "CICover.Tot")
row.names(with.selection) <- delta.multiplier
kable(with.selection, digits=c(rep(1,3), rep(2,3)), 
      caption="Results using chosen model")


## ----matplot, echo=FALSE-----------------------------------------------------------------
matplot(delta.multiplier, pctbias, type="b", lwd=3, pch=20, xlab="Delta", 
        ylab="Percent bias", col=1, main="Bias in estimated density")
legend("bottom", lty=1:3, lwd=3, legend=c("North", "South", "Total"))
abline(h=0)

matplot(delta.multiplier, ci.cover, type="b", lwd=3, pch=20, xlab="Delta", 
        ylim=c(0.75,1),
        ylab="Confidence interval coverage", col=1, main="Confidence interval coverage")
legend("bottom", lty=1:3, lwd=3, legend=c("North", "South", "Total"))
abline(h=0.95)


## ----modsel------------------------------------------------------------------------------
plot(delta.multiplier, modelsel, 
     main="Stratum-specific model chosen", type="b", pch=20,
     xlab="Delta", ylab="Stratum covariate chosen")
abline(h=0.50)

```

**Comment by erex** [comment] 2021-07-31 06:38
More details about the error reported above.  A more detailed error message:

```
'data' must be of a vector type, was 'NULL' 
Calls: <anonymous> ... store.dht.results -> as.matrix -> as.matrix.default -> array
Execution halted
```

so this error is coming from `store.dht.results`.  As the simulation is only of individuals, not groups, the error must come from the three lines beginning with [this one](https://github.com/DistanceDevelopment/dsims/blob/e090a9e59d7e1d8225b51d919d9955b1d09589a5/R/store.dht.results.R#L22)

**Comment by LHMarshall** [comment] 2021-08-18 09:18
Thanks for that extra info @erex

**Comment by LHMarshall** [comment] 2021-08-18 09:46
@erex just working through your example - I see you are running multiple simulations with different sigma parameters for stratum 2 and also for each sigma value one simulation just fitting a half-normal and one simulation choosing between an intercept only half normal and one where sigma varies by stratum. So 28 simulations in total... any ideas which combination of sigma values and analysis options were generating the errors? Thanks

**Comment by erex** [comment] 2021-08-18 10:12
You are right, it is a complex simulation running over a variety of scenarios.  Unfortunately, I can't detect a pattern in where the simulations fail.  Sometimes early in the simulation, sometimes late in the simulation.  That is why I suggested the problem might be hard to track down.  

The error message does seem to suggest something is empty (NULL) where numbers are expected in the three lines of code that generate the complaint.

**Comment by LHMarshall** [comment] 2021-08-18 10:12
Run for sigma option I thought might be most problematic with model selection and worked ok

```
i=14
>   whichmodel[[i]] <- run.simulation(whichmodel.sim, run.parallel = TRUE)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07m 11s
Summary of warnings and errors:
Error: No models could be fitted. (Model number: 1)  (occurred  1  times)
simpleWarning in ddf.ds(model = dsmodel, data, meta.data = meta.data, control = control, : Model fitting did not converge. Try different initial values or different model
 (Model number: 1)  (occurred  1  times)
-----
summary(whichmodel[[14]])

Region:  minkes
No. Repetitions:  90
No. Excluded Repetitions:  1
Using only repetitions where all models converged.

Design:  Systematic parallel line design Systematic parallel line design
   design.type :  Systematic parallel line design 
Systematic parallel line design
   bounding.shape :  rectangle
   samplers :  40
   design.angle :  50 40
   edge.protocol :  minus minus

Population Detectability Summary:
    key.function  =  hn
    scale.param  =  0.6 1.44
    truncation  =  0.8

Analysis Summary:
   Candidate Models:
      Model 1: key function 'hn', formula '~1', was selected 56 time(s).
      Model 2: key function 'hn', formula '~Region.Label', was selected 33
 time(s).
   criteria  =  AIC
   variance.estimator  =  R2
   truncation  =  0.8

Summary for Individuals

Summary Statistics

      mean.Cover.Area mean.Effort    mean.n   mean.k    mean.ER  mean.se.ER
North        9462.671    5914.169 148.93258 23.05618 0.02518267 0.002028595
South        5205.392    3253.370  65.60674 23.05618 0.02016573 0.002326808
Total       14668.063    9167.539 214.53933 23.05618 0.02340250 0.001614450
       sd.mean.ER
North 0.001911849
South 0.002497155
Total 0.001571305

     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Estimates of Abundance (N)

      Truth mean.Estimate percent.bias   RMSE CI.coverage.prob mean.se
North  1935       2012.86         4.02 241.87             0.89  214.23
South  1065       1009.35        -5.22 218.13             0.81  202.35
Total  3000       3022.22         0.74 298.32             0.96  333.64
      sd.of.means
North      230.29
South      212.11
Total      299.17

     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Estimates of Density (D)

           Truth mean.Estimate percent.bias        RMSE CI.coverage.prob
North 0.01667872    0.01734986    4.0239135 0.002084816        0.8876404
South 0.01668437    0.01581263   -5.2248996 0.003417225        0.8089888
Total 0.01668073    0.01680426    0.7405848 0.001658709        0.9550562
          mean.se sd.of.means
North 0.001846549 0.001985020
South 0.003169990 0.003322884
Total 0.001855126 0.001663474

     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Detection Function Values

  mean.observed.Pa mean.estimate.Pa sd.estimate.Pa mean.ESW sd.ESW
1             0.88             0.87           0.06      0.7   0.05
```

**Comment by LHMarshall** [comment] 2021-08-18 10:21
@erex when you say "Sometimes early in the simulation, sometimes late in the simulation." do you mean in an individual simulation or in the set of simulations? i.e. they seems to be failing across the different sigma values? Those lines of code are extracting things from a dht object generated by mrds hmm I'll try for the smallest sigma value maybe there is is an issue when there are no detections in northern stratum but seems an unlikely scenario for this setup. 
![Screenshot 2021-08-18 at 11 10 34](https://user-images.githubusercontent.com/1295691/129882058-3c00a784-bbf7-402f-9988-e91dc2be27b6.png)

**Comment by LHMarshall** [comment] 2021-08-18 10:22
I'm going to leave it running overnight for much longer but I can only do one scenario at a time for debugging purposes.

**Comment by LHMarshall** [comment] 2021-08-18 10:34
Example with the smallest sigma for the northern strata ran without any errors or warnings
```
>   whichmodel[[i]] <- run.simulation(whichmodel.sim, run.parallel = TRUE)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=08m 59s

Region:  minkes
No. Repetitions:  90
No. Excluded Repetitions:  0
Using only repetitions where all models converged.

Design:  Systematic parallel line design Systematic parallel line design
   design.type :  Systematic parallel line design Systematic parallel line design
   bounding.shape :  rectangle
   samplers :  40
   design.angle :  50 40
   edge.protocol :  minus minus

Population Detectability Summary:
    key.function  =  hn
    scale.param  =  0.6 0.24
    truncation  =  0.8

Analysis Summary:
   Candidate Models:
      Model 1: key function 'hn', formula '~1', was selected 0 time(s).
      Model 2: key function 'hn', formula '~Region.Label', was selected 90 time(s).
   criteria  =  AIC
   variance.estimator  =  R2
   truncation  =  0.8

Summary for Individuals

Summary Statistics

      mean.Cover.Area mean.Effort    mean.n   mean.k    mean.ER  mean.se.ER  sd.mean.ER
North        9460.004    5912.502  59.86667 23.12222 0.01012568 0.001301707 0.001291111
South        5202.556    3251.598  66.53333 23.12222 0.02046269 0.002431173 0.002551968
Total       14662.560    9164.100 126.40000 23.12222 0.01379362 0.001489146 0.001319355

     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Estimates of Abundance (N)

      Truth mean.Estimate percent.bias   RMSE CI.coverage.prob mean.se sd.of.means
North  1935       1995.15         3.11 312.90             0.93  322.53      308.79
South  1065       1082.61         1.65 167.98             0.99  182.75      167.99
Total  3000       3077.75         2.59 387.29             0.94  372.51      381.54

     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Estimates of Density (D)

           Truth mean.Estimate percent.bias        RMSE CI.coverage.prob     mean.se sd.of.means
North 0.01667872    0.01719716     3.108391 0.002697044        0.9333333 0.002780043 0.002661574
South 0.01668437    0.01696020     1.653217 0.002631654        0.9888889 0.002862997 0.002631821
Total 0.01668073    0.01711306     2.591804 0.002153453        0.9444444 0.002071261 0.002121427

     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Detection Function Values

  mean.observed.Pa mean.estimate.Pa sd.estimate.Pa mean.ESW sd.ESW
1             0.52             0.51           0.04     0.41   0.03
```

**Comment by erex** [comment] 2021-08-18 10:35
Failures seem to occur for any values of sigma.  As you see, the simulation suite takes more than a few hours to run.  I've started the simulation suite maybe ~50 times;  sometimes simulation failure is after 10 minutes, other times simulation falls over after several hours.

**Comment by LHMarshall** [comment] 2021-08-18 10:37
@erex I have done a wee bit of work in this area already so I may have fixed it while I was fixing something else. I'll run for many more reps on my home desktop over the next few nights for the more extreme combinations and see what happens.

**Comment by LHMarshall** [comment] 2021-08-18 10:41
@erex hmm interesting.... but when it fails the way your code is set up any simulations which have completed will be stored in your lists so it should be possible to tell which analysis it failed with and which sigma although the timings to suggest that it can fails with different sigma. The variability in timing will just be down to a particular chance event happening which causes an issue in the model fitting / dht calculations. I did find one scenario in testing over the last few days where a model which should have been rejected was being passed further on that is now fixed.

**Comment by erex** [comment] 2021-08-18 11:07
sorry, been running the simulations as markdown sessions, so legacy information is not retained when the "knit" fails.

**Comment by LHMarshall** [comment] 2021-08-20 17:52
I have reproduced the error, it happened for the 28th simulation. I have run over 5,000 reps in serial with that particular simulation and could not get it to happen again. I am now running 10,000 reps in parallel with that particular simulation and trying to find a seed so I can narrow it down.

**Comment by erex** [comment] 2021-08-20 18:31
Thanks Laura, that's determination to get the bug to show itself.

**Comment by LHMarshall** [comment] 2021-08-20 23:04
@erex well I seem to have found a memory bug but after 8000 reps in parallel (which is potentially going to be a real pain to sort) still not got this bug to show itself with a useful reproducible seed though! Trying the for loop again with options in case it is something particular to that setup... the hunt continues!

**Comment by LHMarshall** [comment] 2021-08-20 23:38
Nope... Hmm apparently the way to irradicate this bug is to set a seed!

**Comment by LHMarshall** [comment] 2021-08-21 00:31
Ah ha... got ya! set.seed(566) within single.sim.loop generates the error in both parallel and serial simulations.

This was the problematic model which had been selected, with the ddf object plot and details below (the dht part was NULL). It fitted with warning "simpleWarning in ddf.ds(model = dsmodel, data, meta.data = meta.data, control = control, : First partial hessian is singular; using second-partial hessian\n\n (Model number: 2)"

@dill can I please consult... I do a few ddf checks but this one slipped through as a valid model. Should the above warning indicate a model should be discarded or is there some other signal (like the dht part being NULL!)? Thanks! If you can spot any other checks I should be doing (while doing my blind model fitting) that would also be much appreciated... checks can be found [here](https://github.com/DistanceDevelopment/dsims/blob/master/R/DS.Analysis.R) in lines 219-228 Many thanks :) 

![Rplot](https://user-images.githubusercontent.com/1295691/130304119-457479bd-627f-42db-abae-be28e9211f47.png)



```
List of 17
 $ call          : language ddf(dsmodel = ~mcds(key = "hn", formula = ~Region.Label), data = data, method = "ds", meta.data = meta.data,     | __truncated__
 $ data          :'data.frame':	104 obs. of  9 variables:
  ..$ object      : int [1:104] 1 2 3 4 5 6 7 8 9 10 ...
  ..$ individual  : int [1:104] 140 465 907 348 448 638 908 938 1011 17 ...
  ..$ Region.Label: chr [1:104] "South" "South" "South" "South" ...
  ..$ Sample.Label: int [1:104] 1 1 2 3 3 3 3 3 3 4 ...
  ..$ distance    : num [1:104] 0.501 0.504 0.532 0.791 0.578 ...
  ..$ x           : num [1:104] -11.41 -9.88 25.2 85.93 22.63 ...
  ..$ y           : num [1:104] 502 504 508 532 480 ...
  ..$ observer    : num [1:104] 1 1 1 1 1 1 1 1 1 1 ...
  ..$ detected    : num [1:104] 1 1 1 1 1 1 1 1 1 1 ...
 $ model         : symbol dsmodel
 $ meta.data     :List of 7
  ..$ width      : num 0.8
  ..$ point      : logi FALSE
  ..$ binned     : logi FALSE
  ..$ mono       : logi FALSE
  ..$ mono.strict: logi FALSE
  ..$ left       : num 0
  ..$ int.range  : num [1:2] 0 0.8
 $ control       :List of 19
  ..$ optimx.method: chr "nlminb"
  ..$ showit       : num 0
  ..$ estimate     : logi TRUE
  ..$ refit        : logi TRUE
  ..$ nrefits      : num 25
  ..$ initial      : logi NA
  ..$ lowerbounds  : logi NA
  ..$ upperbounds  : logi NA
  ..$ limit        : logi TRUE
  ..$ parscale     : logi TRUE
  ..$ maxiter      : num 12
  ..$ standardize  : logi TRUE
  ..$ mono.points  : num 20
  ..$ mono.tol     : num 1e-08
  ..$ mono.delta   : num 1e-07
  ..$ debug        : logi FALSE
  ..$ nofit        : logi FALSE
  ..$ optimx.maxit : num 300
  ..$ silent       : logi FALSE
 $ method        : chr "ds"
 $ ds            :List of 18
  ..$ X.Intercept.     : num -1.49
  ..$ Region.LabelSouth: num 9.89
  ..$ value            : num -44.6
  ..$ fevals           : num 36
  ..$ gevals           : num 97
  ..$ niter            : num 28
  ..$ kkt1             : logi NA
  ..$ kkt2             : logi NA
  ..$ xtimes           : num 0.1
  ..$ par              : Named num [1:2] -1.49 9.89
  .. ..- attr(*, "names")= chr [1:2] "X.Intercept." "Region.LabelSouth"
  ..$ message          : chr ""
  ..$ hessian          : logi NA
  ..$ aux              :List of 30
  .. ..$ maxit           : num 300
  .. ..$ parscale        : logi TRUE
  .. ..$ follow.on       : logi TRUE
  .. ..$ lower           : num [1:2] -3.341 0.134
  .. ..$ upper           : num [1:2] -1.11 2.13
  .. ..$ setlower        : logi FALSE
  .. ..$ setupper        : logi FALSE
  .. ..$ point           : logi FALSE
  .. ..$ int.range       : num [1:2] 0 0.8
  .. ..$ showit          : num 0
  .. ..$ integral.numeric: NULL
  .. ..$ breaks          : NULL
  .. ..$ maxiter         : num 12
  .. ..$ refit           : logi TRUE
  .. ..$ nrefits         : num 25
  .. ..$ parscale        : logi TRUE
  .. ..$ mono            : logi FALSE
  .. ..$ mono.strict     : logi FALSE
  .. ..$ binned          : logi FALSE
  .. ..$ width           : num 0.8
  .. ..$ standardize     : logi TRUE
  .. ..$ mono.points     : num 20
  .. ..$ mono.tol        : num 1e-08
  .. ..$ mono.delta      : num 1e-07
  .. ..$ debug           : logi FALSE
  .. ..$ nofit           : logi FALSE
  .. ..$ left            : num 0
  .. ..$ silent          : logi FALSE
  .. ..$ optim.history   : logi [1:4] NA NA NA NA
  .. ..$ ddfobj          :List of 4
  .. .. ..$ type          : chr "hn"
  .. .. ..$ scale         :List of 3
  .. .. .. ..$ formula   : chr "~Region.Label"
  .. .. .. ..$ dm        : num [1:104, 1:2] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:104] "1" "2" "3" "4" ...
  .. .. .. .. .. ..$ : chr [1:2] "(Intercept)" "Region.LabelSouth"
  .. .. .. .. ..- attr(*, "assign")= int [1:2] 0 1
  .. .. .. .. ..- attr(*, "contrasts")=List of 1
  .. .. .. .. .. ..$ Region.Label: chr "contr.treatment"
  .. .. .. ..$ parameters: Named num [1:2] -1.49 9.89
  .. .. .. .. ..- attr(*, "names")= chr [1:2] "X.Intercept." "Region.LabelSouth"
  .. .. ..$ xmat          :'data.frame':	104 obs. of  6 variables:
  .. .. .. ..$ object      : int [1:104] 1 2 3 4 5 6 7 8 9 10 ...
  .. .. .. ..$ Region.Label: chr [1:104] "South" "South" "South" "South" ...
  .. .. .. ..$ distance    : num [1:104] 0.501 0.504 0.532 0.791 0.578 ...
  .. .. .. ..$ binned      : logi [1:104] FALSE FALSE FALSE FALSE FALSE FALSE ...
  .. .. .. ..$ observer    : num [1:104] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. ..$ detected    : num [1:104] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..$ intercept.only: logi FALSE
  ..$ model            :List of 1
  .. ..$ scalemodel: NULL
  ..$ converge         : num 0
  ..$ bounded          : logi FALSE
  ..$ bounds           :List of 4
  .. ..$ lower   : num [1:2] -3.341 0.134
  .. ..$ upper   : num [1:2] -1.11 10.8
  .. ..$ setlower: logi FALSE
  .. ..$ setupper: logi FALSE
  ..$ optim.history    : num [1:6, 1:4] 0 0 0 0 1 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:6] "" "" "" "" ...
  .. .. ..$ : chr [1:4] "" "" "X.Intercept." "Region.LabelSouth"
  ..- attr(*, "details")='data.frame':	1 obs. of  5 variables:
  .. ..$ method : chr "nlminb"
  .. ..$ ngatend: logi NA
  .. ..$ nhatend: logi NA
  .. ..$ hev    : logi NA
  .. ..$ message: chr "none"
  ..- attr(*, "maximize")= logi FALSE
  ..- attr(*, "npar")= int 2
  ..- attr(*, "class")= chr [1:2] "mcds" "ds"
 $ par           : Named num [1:2] -1.49 9.89
  ..- attr(*, "names")= chr [1:2] "X.Intercept." "Region.LabelSouth"
 $ lnl           : num 44.6
 $ hessian       : logi NA
 $ dsmodel       : chr [1:2] "~" "mcds(key = \"hn\", formula = ~Region.Label)"
 $ criterion     : num -85.1
 $ fitted        : Named num [1:104] 1 1 1 1 1 ...
  ..- attr(*, "names")= chr [1:104] "1" "2" "3" "4" ...
 $ Nhat          : num 176
 $ name.message  : chr "half-normal key function"
 $ model.index   : int 2
 $ delta.criteria: num 30.2
 - attr(*, "class")= chr [1:2] "ds" "ddf"
 
 ```

**Comment by erex** [comment] 2021-08-21 06:29
I'll spark up a new simulation with a seed and see what happens.

**Comment by erex** [comment] 2021-08-21 07:50
Afraid it doesn't take many reps for the simulation to fall over on my computer.  This is with a set.seed().  Result from the first code block simulation (chunk label `loopsigma`) with number of replicates`num.sim` set at 200
```
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04m 23s
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04m 52s
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04m 32s
  |+++++++++++                                       | 21% ~03m 59s      Error in checkForRemoteErrors(val) : 
  one node produced an error: 'data' must be of a vector type, was 'NULL'
```
That seems to fall over after 200x3~600 replicates.

**Comment by LHMarshall** [comment] 2021-08-21 16:06
@erex see my most recent comment I found the bug (after ~15,000 seeded repetitions!!!)... it eventually fell over with a seed set so I could get a single reproducible dataset. Seems for the odd dataset a model with strata in as a covariate, for one of the strata a flat detection function was fitted and this caused a first partial hessian is singular warning. I am now awaiting advice from Dave as to whether all models with this warning should be discarded and if there are any other checks beyond what I currently do to ensure only valid ddf models get through to the dht stage. Currently ddf warnings are stored but do not get the model chucked out unless there was no convergence or fitted values >1. I've just added functionality to store the iteration number of warnings too so the user can later remove these reps if they wish. I have seen this warning before but it has never led to the dht results being NULL before.

**Comment by LHMarshall** [comment] 2021-08-21 16:37
A reproducible single repetition example can be found in this [branch](https://github.com/DistanceDevelopment/dsims/tree/Difficult-to-reproduce-error)

**Comment by dill** [comment] 2021-08-23 09:21
On the Hessian issue. That could indicate that something has gone wrong with the optimization, usually this means that you might want to be cautious about the resulting uncertainty estimates, but they *might* be fine (just that they were hard to compute numerically). 

In this particular case we see that the `$hessian` element is `NA`. In this case [`ds` will not call `dht`](https://github.com/DistanceDevelopment/Distance/blob/master/R/ds.R#L705), hence the `NULL` entry. That's probably worth putting in as a check in your code.

**Comment by LHMarshall** [comment] 2021-08-25 11:28
@dill thanks :)

**Closed** 2021-08-25 12:06 UTC
